export const CUTTHROAT_SELECTORS = {
  wrapper: '#cutthroat-game-wrapper',
  tableBottom: '.table-bottom',
  deck: '[data-cy=cutthroat-deck]',
  scrap: '[data-cy=cutthroat-scrap]',
  historyDesktop: '.history-panel-desktop',
  historyLog: '[data-cy=cutthroat-history-log]',
  spectatorListButton: '[data-cy=spectate-list-button]',
  spectatorListMenu: '[data-cy=spectate-list-menu]',
  seatStatuses: '[data-cy^=cutthroat-seat-status-]',
  seatTurns: '[data-cy^=cutthroat-seat-turn-]',
  seatPoints: '[data-cy^=cutthroat-seat-points-]',
  seatGoals: '[data-cy^=cutthroat-seat-goal-]',
  turnIndicator: '.turn-status',
};
